spring:
  datasource:
    url: jdbc:mysql://47.97.43.25:3306/wangfan
    username: root
    password: WangFan1216..
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdel: 5
    maxActive: 20
    ###获取连接等待超时的时间
    maxWait: 60000
    ###间隔 进行一次检测，需要关闭的空闲连接、单位是毫秒
    timeBetweenEvictionRunsMillis: 60000

    ### 连接在池中的最小生存时间 ms
    minEvictableIdleTimeMillis: 300000
    dbcp2:
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      ###打开psCache，并指定每个连接上psCache的大小
      pool-prepared-statements: true
    ###通过配置connectProperties属性来打开mergeSql功能；慢sql记录
    connectProperties: durid.stat.mergeSql=true;durid.stat.slowSqlMillis=5000
    ###合并多个DuridDataSource的监控数据
    useGlobalDataSourceStat: true

  jpa:
    show-sql: true

